# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Juliano Petronetto"
description: > # this means to ignore newlines until "email:"
   Desenvolvimento web e mobile, Machine Learning, DevOps e coisas do tipo.

# email: a-mail@mail.mail
#blog logo
logo: "/assets/images/logo.jpg"
float_logo: true # true, false (default)
google_analytics: UA-98708697-1

lang: "pt-BR"

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Juliano Petronetto'
author: 'Juliano Petronetto'
bio: 'Desenvolvedor full-stack, está estudando Machine Learning e promete criar a Skynet'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://petronetto.github.io" # the base hostname & protocol for your site
baseurl: ""
permalink: /:year/:month/:day/:title
#used to display twitter cards
twitter_handle: '@jpetronetto'

#fill in disqus shortname to use disqus
disqus: petronetto

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/jpetronetto
    desc: Não me siga no twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/JulianoPetronetto
    desc: Não me adicione no facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="
 
  - icon:	github
    url:	https://github.com/petronetto
    desc:	Fork no github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
